### ISSUE TITLE
After following the readme instruction "no such module PNChartSwift"

### ISSUE THREAD

**Issue by hanachan1026** [kevinzhow/PNChart-Swift#73]
Hi,  I get " no such module ~~" after following the instruction

First,
I did write **pod 'PNChartSwift',:git => 'https://github.com/kevinzhow/PNChart-Swift.git'**
to Podfile and **pod install**

And open project.xcworkspace

And I get " no such module ~~"

I think this cloning the wrong directory

I see only  AppDelegate.swift, ViewController.swift and Support Files. I think this cloning 'kevinzhow/PNChart-Swift/PNChartSwift'

Please fix this, thank you.

**Comment by lenkaiser** [comment]
I have fixed it in my own fork:

pod 'PNChartSwift', :git => 'https://github.com/lenkaiser/PNChart-Swift'

**Comment by jjstyle0427** [comment]
@lenkaiser 
it work!!
but I still can't find PNLineChart...

**Comment by lenkaiser** [comment]
I'm working on it!

**Comment by Bijiabo** [comment]
Still this doesn't work.

**Comment by denish09** [comment]
I still can't find PNPieChart...
Can't any methods used in PNPiecharts
Please help me....
